### ISSUE TITLE
Any chance for some more I instructions? 

### ISSUE THREAD

**Issue by oshaboy** [NinjaWeedle/HyperWaveCHIP-64#1]
I've been writing a game for the Chip-8 and the lack of a way to `Push I` and `Pop I` from and to the stack is getting to me. Also `Sub I, Vx` and maybe a `LD I, V1` and `LD V1, I` to copy I to and from the General Purpose register pair V0, V1. 

Having I be a write only register is a pain and if you're already extending the architecture might as well add those in too.

**Comment by NinjaWeedle** [comment]
You can't just have an instruction to load I to a register. I is a 16-bit pointer, and the registers are all 8-bi, meaning I can be much larger than the registers. I should not be used to store values, because it is used so often for sprites and audio. If you want to set I to a specific value, make a subroutine that your game can call to with an Annn or Long i (0xF000) instruction to set i to your desired value (or just call either one of those functions directly). You shouldn't need to have an instruction to read the i pointer to know where your i pointer is.  

You can kind of already set I to a register anyway- Fx29 and Fx30 do this. while these instructions can't use every single value from 0-255, a register loaded to I would only be able to reach the font data anyway- so what's the point of having another  instruction for it?

**Comment by oshaboy** [comment]
> You can't just have an instruction to load I to a register. 
I said register pair. So copy the high byte from V0 and the low byte from V1. Kinda like how memory works. 

I want a subroutine in my game that takes an arbitrary sprite, draws it, and then updates an arbitrary memory address associated with it. Can't do it because I can only pass one pointer to a subroutine. Instead I have to set a register and the caller has to update the memory address. If I could either pass pointers on the stack or through the GP register the subroutine could do everything. 

I also have another one that draws one of 2 sprites based on some condition. The way I did it was pass the offset between the sprites. But because I can only Add to I and not subtract from it I need 2 copies of one of the sprites (one call draws either A or B and the other draws either B or A, so I need A to be both before and after B).

**Comment by Kouzeru** [comment]
You can try pass pointer of pointers, and do some self modifying memory. Here example code in Octo
```
: main
i := spiteargs
call drawbody
loop again

: drawbody
load v5
i := sbcA
save v1
v0 := v2
v1 := v3
i := sbcB
save v1
: sbcA
0 0
sprite v4 v5 8
v5 += 8
: sbcB
0 0
sprite v4 v5 8
return

: spriteargs
i := sprite1destination
i := sprite2destination
32 # x pos
12 # y pos

: sprite1destination
0b00111100
0b01000010
0b10000001
0b10000001
0b10000001
0b10000001
0b01000010
0b00111100

: sprite2destination
0b00011000
0b01111110
0b10011001
0b10011001
0b00111100
0b01000010
0b10000001
0b10000001
```

Note you may need to backup your regs before the call

**Comment by oshaboy** [comment]
Self Modifying Code 🤮

Yeah I know I can do it but I prefer to avoid it whenever possible. It sounds like hell to debug if something goes wrong.

**Comment by NinjaWeedle** [comment]
I think PUSH and POP I would be unnecessary, as mixing pc and I in the same stack is very difficult for the programmer to work with. You’re better off creating a second stack in ram using SMC for I. Hyperwavechip-64 lets you effectively use all 64KB of ram for code already, so making room for  another stack shouldn't be an issue.

However, the `Sub I, Vx` thing is something I’m warming up to. There are a couple uses for decrementing I, and giving it an opcode like Fx1F would pair nicely with Fx1E, `Add I, Vx`.

**Comment by Kouzeru** [comment]
You better do it to make it playable for the thousands of emulator out there :)

**Comment by NinjaWeedle** [comment]
Fx1F (Sub I, Vx) has been implemented. I'm rejecting the other two opcode suggestions.

**Comment by oshaboy** [comment]
Cool. Thanks.
